spring:
  application:
    name: linkedmap
  datasource:
#    driverClassName=org: mariadb:jdbc:Driver
#    url: jdbc:mariadb://localhost:3306/linkedmap
#    username: hyeonho
#    password: dkflfkd4640@@
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update  #엔티티 정보를 지우고 다시 생성
#      ddl-auto: create-drop  #엔티티 정보를 지우고 다시 생성

    properties:
      hibernate:
        #show_sql: true  #System.out에 출력
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  #하이버네이트가 생성하는 SQL 콘솔로깅
    org.hibernate.type: trace #쿼리 파라미터 로그 남기기
